version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  wallet:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/walletdb
      DB_USERNAME: walletuser
      DB_PASSWORD: secret123
      JWT_EXPIRATION: 86400000
    depends_on:
      - db

volumes:
  db_data:
